### ISSUE TITLE
Getting stuck with non 90 degree rotations/movements

### ISSUE THREAD

**Issue by Tushar-N** [allenai/ai2thor#322] opened 2019-12-20 19:11 UTC
I'm trying to move using `RotateLook` and `MoveAhead` but on several floorplans, the agent gets stuck and cannot move. Here's an example.

```
import ai2thor.controller 
controller = ai2thor.controller.Controller() 
controller.start() 
 
controller.reset('FloorPlan4') 
event = controller.step(dict(action='Initialize', gridSize=0.25))

# back up into position
for _ in range(5):
	event = controller.step(dict(action='MoveBack'))

# Rotate right 30 degrees and step forward
event = controller.step(dict(action='RotateLook', rotation=270+30))
event = controller.step(dict(action='MoveAhead'))
# Now stuck. Cannot move in any direction.

# Escape attempt 1: Fails
event = controller.step(dict(action='MoveBack'))

# Escape attempt 2: Fails
event = controller.step(dict(action='RotateLeft'))
event = controller.step(dict(action='MoveAhead'))

```

I thought that if the agent is going to clip into the environment or get stuck, the action would fail. Is the simulator designed to only handle 90 degree rotations?

**Comment by winthos** [comment] 2019-12-20 21:56
So the default initialization of the framework assumes only 90 degree rotations on a grid defined by gridSize starting from the agent's initial position. One check done in the background is that after a successful movement, the agent is snapped to the closest grid point in order to account for jittering due to physics, or accumulating floating point errors in unity's positioning. 

Because of this, when rotating with a non-orthogonal angle, the MoveAhead check will correctly check collision, but after moving to the "off grid" position, it is immediately snapping to the closest grid point, causing you to get trapped in some areas.

To avoid this, on the Initialize action, set the `continuous` parameter to `True`, which will ignore this automatic snapping:

```event = controller.step(dict(action='Initialize', gridSize=0.25, continuous = True))```

**Comment by Tushar-N** [comment] 2019-12-20 22:18
Thanks for the reply and the explanation!

Couple of things:
- I just tried using `continuous=True` with the snippet I provided above, and it still gets stuck at the final position. I'm wondering if it is a different issue here?
- Is there a way to prevent snapping to grid points where the agent will be trapped? i.e. still stay on the default grid, but just snap back to the nearest _safe_ grid point instead of the nearest grid point in general (or else just fail). 
- Related to the above, are all the positions given by `GetReachablePositions` guaranteed to leave the agent un-trapped? Can I just make sure my movement is restricted to this set of positions. I can check manually before every step (the same way `MoveAhead` checks for off-grid), but I just wanted to make sure there's no better way.

**Comment by winthos** [comment] 2019-12-20 22:49
- If `continuous = True` is still not working, it might have something to do with the `RotateLook` action you are using. That is no longer documented as it has been deprecated, so it may be having some unforeseen interactions with how the current iteration of `MoveAhead` works.

- There is not currently a way to prevent snapping selectively in regards to a last safe grid point.

- This solution could work. All positions returned by `GetReachablePositions` are guaranteed as valid movements, so restricting positions to the set returned by get reachable.

Additionally, if you could provide metadata information like the agent's position when it gets stuck, even after using `continuous = True`, we maybe be able to further debug the issue.

**Comment by Tushar-N** [comment] 2019-12-21 01:03
>  That is no longer documented as it has been deprecated, so it may be having some unforeseen interactions with how the current iteration of MoveAhead works.

Is there a more appropriate way to rotate the agent by a non-orthogonal angle? Should I just be using `TeleportFull` for all my movement if I _do_ require finer grained movement?

Here's the metadata with `continuous=True` after executing the code I provided in the first post. 

<details><summary>event.metadata['agent']</summary>
<p>

```python
{'name': 'agent',
 'position': {'x': -1.0, 'y': 0.9009999, 'z': 1.5},
 'rotation': {'x': 0.0, 'y': 270.0, 'z': 0.0},
 'cameraHorizon': 0.0,
 'visible': False,
 'receptacle': False,
 'toggleable': False,
 'isToggled': False,
 'breakable': False,
 'isBroken': False,
 'canFillWithLiquid': False,
 'isFilledWithLiquid': False,
 'dirtyable': False,
 'isDirty': False,
 'canBeUsedUp': False,
 'isUsedUp': False,
 'cookable': False,
 'isCooked': False,
 'ObjectTemperature': None,
 'canChangeTempToHot': False,
 'canChangeTempToCold': False,
 'sliceable': False,
 'isSliced': False,
 'openable': False,
 'isOpen': False,
 'pickupable': False,
 'isPickedUp': False,
 'mass': 0.0,
 'salientMaterials': None,
 'receptacleObjectIds': None,
 'distance': 0.0,
 'objectType': None,
 'objectId': None,
 'parentReceptacle': None,
 'parentReceptacles': None,
 'currentTime': 0.0,
 'isMoving': False,
 'objectBounds': None}
```

</p>
</details>

**Comment by mattdeitke** [comment] 2020-08-14 01:33
Merging with #370 as the issue is now solved there.

**Closed by mattdeitke** 2020-08-14 01:33 UTC

**Comment by zkytony** [comment] 2021-05-28 18:56
I ran into this issue again, and `continuous=True`, `snapToGrid=False` and the `rotateStepDegrees` in #370 didn't resolve it for me.

Here's a minimal example (tested with 2.7.2; feel free to try it out in a newer version and see what happens).

First I tried using the `degrees` parameter in the `step(action='RotateLeft')` or `step(action='RotateRight')`  calls, with `continuous=True`:
```python
import ai2thor.controller
import time
import cv2

STEP_COUNT=0
def saveimg(event):
    global STEP_COUNT
    cv2.imwrite("step%d.png" % STEP_COUNT, event.cv2img)
    STEP_COUNT += 1

rotation_degrees = 45

c = ai2thor.controller.Controller(continuous=True, scene='FloorPlan1')
saveimg(c.step(action="Pass"))
# facing the fridge initially
event = c.step(action='RotateLeft', degrees=rotation_degrees); saveimg(event)
event = c.step(action='RotateLeft', degrees=rotation_degrees); saveimg(event)
# now facing stove

event = c.step(action='RotateLeft', degrees=rotation_degrees); saveimg(event)
# now at 45 degree towards the table

event = c.step(action='MoveAhead', degrees=rotation_degrees); saveimg(event)
# gets stuck

event = c.step(action='RotateRight', degrees=rotation_degrees); saveimg(event)
event = c.step(action='RotateRight', degrees=rotation_degrees); saveimg(event)
# turned away from the table

event = c.step(action='MoveAhead', degrees=rotation_degrees); saveimg(event)
# stuck, can't actually move away from the table. Unexpected.
```
The last `MoveAhead` didn't actually move the agent, although it wasn't clear what is blocking it. The agent's view before that action is below:

![step7](https://user-images.githubusercontent.com/7720184/120028386-9e941e80-bfc2-11eb-8087-8c857e356ed2.png)

Then, I tried setting `rotateStepDegrees` when initializing the controller instead of passing `degrees`, the result is the same.
