### ISSUE TITLE
SetObjectToggles not working + Can't turn a desk lamp on/off

### ISSUE THREAD

**Issue by rowanz** [allenai/ai2thor#391] opened 2020-04-23 20:50 UTC
I'm trying to turn off a desk lamp following the [documentation here](https://ai2thor.allenai.org/ithor/documentation/actions/initialization/#set-toggleable-objects-by-object-type), however, it doesn't seem to work. Replication information below:

I'm using `ai2thor==2.4.0` and version `thor-Linux64-202004171404/thor-Linux64-202004171404`

I can encounter the problem when running the following lines of code:
```
from ai2thor.controller import Controller
c = Controller( x_display=0, player_screen_width=300, player_screen_height=300, quality="Very Low", scene='FloorPlan301', agentMode='default', agentControllerType='physics')
event = c.step({"action": "Initialize","gridSize": 0.25,"visibilityDistance": 1.5,"fov": 90.0,"makeAgentsVisible": False,"alwaysReturnVisibleRange": False})
c.step(action='SetObjectToggles', objectToggles=[{'objectType': 'DeskLamp', 'isOn': False}])
```

First, this `SetObjectToggles` fails with the following error:

```
~/anaconda3/envs/house/lib/python3.7/site-packages/ai2thor/controller.py in step(self, action, **action_args)
    691
    692         if not self.last_event.metadata['lastActionSuccess'] and self.last_event.metadata['errorCode'] == 'InvalidAction':
--> 693             raise ValueError(self.last_event.metadata['errorMessage'])
    694
    695         if raise_for_failure:

ValueError: Invalid action: SetObjectToggles
```

Digging further, I can't seem to manually toggle the lamp here, as it doesn't have the `isOn` property that [is referred to here](https://ai2thor.allenai.org/ithor/documentation/objects/actionable-properties/). Running ```desk_lamps = [x for x in event.metadata['objects'] if x['objectType'] == 'DeskLamp']``` gives:

```
[{'name': 'DeskLamp_33ba15a6',
  'position': {'x': -1.31978738, 'y': 1.23870516, 'z': -0.994436145},
  'rotation': {'x': 359.900757, 'y': 89.95341, 'z': 359.986816},
  'visible': False,
  'receptacle': False,
  'toggleable': True,
  'isToggled': True,
  'breakable': False,
  'isBroken': False,
  'canFillWithLiquid': False,
  'isFilledWithLiquid': False,
  'dirtyable': False,
  'isDirty': False,
  'canBeUsedUp': False,
  'isUsedUp': False,
  'cookable': False,
  'isCooked': False,
  'ObjectTemperature': 'RoomTemp',
  'canChangeTempToHot': False,
  'canChangeTempToCold': False,
  'sliceable': False,
  'isSliced': False,
  'openable': False,
  'isOpen': False,
  'pickupable': False,
  'isPickedUp': False,
  'moveable': True,
  'mass': 2.06,
  'salientMaterials': ['Metal', 'Fabric'],
  'receptacleObjectIds': None,
  'distance': 4.10230827,
  'objectType': 'DeskLamp',
  'objectId': 'DeskLamp|-01.32|+01.24|-00.99',
  'parentReceptacles': ['Dresser|-01.33|+00.01|-00.74'],
  'isMoving': False,
  'axisAlignedBoundingBox': {'cornerPoints': [[-1.24880266,
     1.56558228,
     -0.902912259],
    [-1.24880266, 1.56558228, -1.086083],
    [-1.24880266, 1.23842049, -0.902912259],
    [-1.24880266, 1.23842049, -1.086083],
    [-1.390816, 1.56558228, -0.902912259],
    [-1.390816, 1.56558228, -1.086083],
    [-1.390816, 1.23842049, -0.902912259],
    [-1.390816, 1.23842049, -1.086083]],
   'center': {'x': -1.31980932, 'y': 1.40200138, 'z': -0.994497657},
   'size': {'x': 0.142013311, 'y': 0.3271618, 'z': 0.1831708}},
  'objectOrientedBoundingBox': {'cornerPoints': [[-1.24066579,
     1.22984934,
     -1.10477746],
    [-1.24084544, 1.22990012, -0.8839622],
    [-1.39887786, 1.22962642, -0.8840907],
    [-1.39869821, 1.22957551, -1.104906],
    [-1.241268, 1.57760191, -1.10485792],
    [-1.24144769, 1.57765281, -0.88404274],
    [-1.39948022, 1.57737911, -0.884171247],
    [-1.39930058, 1.57732821, -1.10498643]]}}]
```

Any help is much appreciated! thanks :)

**Comment by winthos** [comment] 2020-04-23 21:22
Hello!

For your first issue, this was an error in our documentation. The `SetObjectToggles` action has been deprecated and replaced with a new, more fully featured action called `SetObjectStates`

Instead of only being able to set the `isToggled` state of compatible objects, this new action can also set `isOpen`, `isBroken`, `isFilledWithLiquid`, `isDirty`, `isCooked`, `isSliced`, and `isUsedUp` for all sim objects of a specified type.

The documentation on the website will be updated to reflect this, but for now I will post a quick summary of how to use this action:

```
event = controller.step(action='SetObjectStates', objectType='DeskLamp, stateChange= `toggleable`, `, isToggled=True")
```

Parameters:
- objectType - The object type to apply the specified state change to. 

- stateChange - declares which state that all objects of type `objectType` will be modified. This is explicitly defined because some objects can have multiple state changes (ie: Microwaves can be toggled on via `isToggled`, and can be opened via `isOpen`). Valid state changes are: openable, toggleable, breakable, canFillWithLiquid, dirtyable, cookable, sliceable, canBeUsedUp.

- The last parameter will change depending on which stateChange is set for the `stateChange` parameter. Each state change parameter modifies a specific bool of the object, which will alter that same bool in the object's metadata and also cause the object to visibly change. The bools for each stateChange are as follows: openable (isOpen), toggleable (isToggled), breakable (isBroken), canFillWithLiquid (isFilledWithLiquid), dirtyable (isDirty), cookable (isCooked), sliceable (isSliced), canBeUsedUp (isUsedUp).

For your second issue, this is again due to a clarity issue in the documentation. Objects that can be toggled On/Off manipulate the `isToggled` value of the object. There is no `isOn` metadata value. If you check the documentation for the `ToggleObjectOn` or `ToggleObjectOff` actions [here](https://ai2thor.allenai.org/ithor/documentation/actions/object-interaction/), you will see that it will change the `isToggled` value of the object's metadata. I will also update the documentation to make this more clear.

**Comment by rowanz** [comment] 2020-04-23 22:06
Thanks @winthos for the speedy reply and the helpful clarification!

I wasn't able to use `SetObjectStates` after all -- no matter the parameters, I get the error

`action.SetObjectStates has objectType and stateChange strings null. Please pass in valid strings.`

One other thing I tried is doing the `ToggleObjectOff` manually for the object, running `c.step(action='ToggleObjectOff', objectId=desk_lamps[0]['objectId'])` in my example above. However now I'm getting the following error

```
object not found: DeskLamp|-01.32|+01.24|-00.99System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object\n  at UnityStandardAssets.Characters.FirstPerson.PhysicsRemoteFPSAgentController.ToggleObject (.SimObjPhysics target, Boolean toggleOn, Boolean forceAction) [0x00000] in <filename unknown>:0 \n  at UnityStandardAssets.Characters.FirstPerson.PhysicsRemoteFPSAgentController.ToggleObject (.ServerAction action, Boolean toggleOn, Boolean forceAction) [0x00000] in <filename unknown>:0 \n  at UnityStandardAssets.Characters.FirstPerson.PhysicsRemoteFPSAgentController.ToggleObjectOff (.ServerAction action) [0x00000] in <filename unknown>:0 \n  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (object,object[],System.Exception&)\n  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 \n  --- End of inner exception stack trace ---\n  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 \n  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <filename unknown>:0 \n  at UnityStandardAssets.Characters.FirstPerson.BaseFPSAgentController.ProcessControlCommand (.ServerAction controlCommand) [0x00000] in <filename unknown>:0
```

thanks again! :)

**Comment by winthos** [comment] 2020-04-23 22:13
Try using `forceAction=True` when you use `ToggleObjectOff`, I believe it is failing because by default, objects must be within view of the agent in order to perform the action. Setting `forceAction=True` will allow you to toggle objects using `ToggleObjectOff` and `ToggleObjectOn` no matter where the object is in the scene. If you are still getting a null object even with forceAction set, please give me the exact objectId and the scene you are trying to access that object in to further debug.

As for the `SetObjectStates`, I will investigate that error further and report back as soon as I can.

**Comment by winthos** [comment] 2020-04-23 23:22
Ok, apologies again, but I gave you incorrect syntax for the `SetObjectStates` action. This should be the correct way to call `SetObjectStates`.

```
event = controller.step(action='SetObjectStates', SetObjectStates=[{'objectType': 'DeskLamp', 'stateChange': 'toggleable', 'isToggled': True}])
```

You actually need to set up a `SetObjectStates` object with the parameters for the `objectType`, `stateChange` and bool as members. See if this syntax works for you.

**Comment by winthos** [comment] 2020-04-24 00:37
The documentation for `SetObjectStates` has been updated on the live documentation website.

**Comment by rowanz** [comment] 2020-04-27 21:10
Thanks for looking into this, and for updating the documentation @winthos!

I still seem to have the same issue - running the command above
```
c.step(action='SetObjectStates', SetObjectStates=[{'objectType': 'DeskLamp', 'stateChange': 'toggleable', 'isToggled': False}])
```
gives me the error (under `c.last_event.metadata['errorMessage']`)

> action.SetObjectStates has objectType and stateChange strings null. Please pass in valid strings.

I tried adding `forceAction=True` to the `ToggleObjectOff` command, but that gives me the same "object not found" error as earlier.

Here's the updated minimum working example:
```
from ai2thor.controller import Controller

c = Controller( x_display=0, player_screen_width=300, player_screen_height=300, quality="Very Low", scene='FloorPlan301', agentMode='default', agentControllerType='physics')
event = c.step({"action": "Initialize","gridSize": 0.25,"visibilityDistance": 1.5,"fov": 90.0,"makeAgentsVisible": False,"alwaysReturnVisibleRange": False})

# SetObjectStates
c.step(action='SetObjectStates', SetObjectStates=[{'objectType': 'DeskLamp', 'stateChange': 'toggleable', 'isToggled': False}])


desk_lamps = [x for x in event.metadata['objects'] if x['objectType'] == 'DeskLamp']
# the objectID is DeskLamp|-01.32|+01.24|-00.99
c.step(action='ToggleObjectOff', objectId=desk_lamps[0]['objectId'], forceAction=True)
```

Let me know if I can provide any more help in reproducing this. thanks!

**Comment by mattdeitke** [comment] 2020-04-28 01:16
Hey Rowan!

I was able to reproduce this error. The fix is to pass in `SetObjectStates` as a dictionary, instead of a dictionary nested inside of a list, as in:
```
c.step(action='SetObjectStates', SetObjectStates={'objectType': 'DeskLamp', 'stateChange': 'toggleable', 'isToggled': False})
```
where the `[]` are removed from the SetObjectStates parameter call.

This syntax is also being updated on the documentation as well.

Hope that helps,
Matt :)

**Comment by winthos** [comment] 2020-04-28 01:49
Additionally, I've found the issue with `ToggleObjectOff` not taking the `forceAction` parameter correctly. This will be fixed with a new pip release very soon. (I will update here once it is live).

**Comment by mattdeitke** [comment] 2020-08-14 00:46
Closing as this appears to be solved :)

**Closed by mattdeitke** 2020-08-14 00:46 UTC
