### ISSUE TITLE
Bug for receptacle containers? 

### ISSUE THREAD

**Issue by parsa-m** [allenai/ai2thor#35] opened 2018-03-14 21:10 UTC
So in Floorplan 1 there is a Bread on the table in the middle of the room. However that bread doesn't show up in any of the receptacles of the scene. 
Why is the table not considered a receptacle here? Or is this a bug? I've seen this for many different objects not being contained within a receptacle. 

Thanks 

To reproduce: 
import ai2thor.controller
c = ai2thor.controller.Controller() 
c.docker_enabled = True 
c.start() 
c.reset('FloorPlan1')
e = c.step(dict(action='Initialize', gridSize=0.25))
receptacles = [x for x in e.metadata['objects'] if x['receptacle'] == True]
for r in receptacles:
   print(r['objectId'], r['receptacleObjectIds'])

**Comment by parsa-m** [comment] 2018-06-12 00:56
@ekolve has this issue been fixed? And if so what has changed exactly?

**Comment by ekolve** [comment] 2018-06-12 17:53
Sorry, I closed this with the thought that the issue was not a bug since it is expected, but not desirable behavior.  I reopened it and marked it as an enhancement.  The new version we are working on that uses rigidbody physics won't have this issue, but it may still be worth investigating how to find a solution for these orphaned objects.

**Comment by parsa-m** [comment] 2018-06-12 21:33
Thanks so one of the capabilities I was hoping for is to be able to know what objects are stored in what receptacles so that I can generate instructions such as pick up apple from fridge. Right now that can be generated for the few objects that are correctly recorded under those receptacles. Doing a distance-wise pairing of objects to receptacles can roughly get many of them although with a few mistakes. Adding them manually is also an option since there aren't too many objects and receptacles. 

The biggest enhancement I'm hoping for is being able to randomly place valid objects onto random valid receptacles. Will that be in the new version?

**Comment by danielgordon10** [comment] 2018-06-15 16:56
I would recommend using the randomInitialize action. This will guarantee that objects in the metadata are placed in receptacles, and that there won't be extra objects like bread in the scene. There will still be some things that aren't simObjs placed in the same place they always are like clutter and bottles in the background, but it should fix your bread on table issue.

**Comment by danielgordon10** [comment] 2018-06-15 16:59
Looks like the documentation is missing (will be added shortly), but for now, you can see the randomInitialize command here https://github.com/allenai/ai2thor/blob/master/ai2thor/controller.py#L387

**Comment by parsa-m** [comment] 2018-06-27 05:05
Great thanks!

**Comment by danielgordon10** [comment] 2018-06-27 17:49
Can you close the issue?

**Closed** 2018-06-27 18:32 UTC
Labels: enhancement
