### ISSUE TITLE
Third party camera depth off by 50x

### ISSUE THREAD

**Issue by apoorvkh** [allenai/ai2thor#767] opened 2021-05-21 23:58 UTC
Have noticed an issue, where array elements in `event.third_party_depth_frames[0]` are scaled ~50x smaller than in `event.depth_frame` (when third party camera positioned at approximately same place as agent camera).

https://colab.research.google.com/drive/1E7wPQvyB75bDUeNLwuMKwgdVLhPT4Amt

Reproduced this issue in ai2thor 2.7.2 and 3.2.0.

**Comment by ekolve** [comment] 2021-05-25 04:21
This is caused by the different clipping planes between the current third party camera and the agent's camera.  PR #759 fixes this.  I also added a unit test to ensure that the cameras are aligned going forward.  The PR should get merged in sometime this week.

**Closed** 2021-05-25 20:00 UTC
Labels: bug
