### ISSUE TITLE
Error running "controller.start()"

### ISSUE THREAD

**Issue by YunqiuXu** [allenai/ai2thor#97] opened 2018-11-13 04:07 UTC
I installed ai2thor 0.0.44 successfully on redhat with all requirments satisfied. However when I run "controller.start()" it download a file then throw an error "[Errno 9] Bad file descriptor"

I use python 3.5 based on anaconda 3, following is the error. Could you help me to tackle this?

In [3]: controller.start()
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-3-0866d651d26b> in <module>()
----> 1 controller.start()

~/anaconda3/lib/python3.5/site-packages/ai2thor/controller.py in start(self, port, start_unity, player_screen_width, player_screen_height, x_display)
    762 
    763             self.download_binary()
--> 764             self.lock_release()
    765             self.prune_releases()
    766 

~/anaconda3/lib/python3.5/site-packages/ai2thor/controller.py in lock_release(self)
    443         if os.path.isdir(build_dir):
    444             self.lock_file = open(os.path.join(build_dir, ".lock"), "w")
--> 445             fcntl.flock(self.lock_file, fcntl.LOCK_SH)
    446 
    447     def prune_releases(self):

OSError: [Errno 9] Bad file descriptor

**Comment by ekolve** [comment] 2018-11-13 04:56
What version of RedHat are you using? and can you run the following snippet below? Please post the output from the script.  If possible, run the script with the system supplied python2 or python3 as well.  You can avoid the ai2thor._builds import if you hardcode in the value that get assigned to `build_name`. 

```python
import os
from ai2thor._builds import BUILDS
import platform
import fcntl

base_dir = os.path.join(os.path.expanduser('~'), '.ai2thor')
releases_dir = os.path.join(base_dir, 'releases')
build_name = os.path.splitext(os.path.basename(BUILDS[platform.system()]['url']))[0]

print("base dir: %s" % base_dir)
print("releases dir: %s" % releases_dir)
print("build name: %s" % build_name)


build_dir = os.path.join(releases_dir, build_name)
if os.path.isdir(build_dir):
    lock_file = open(os.path.join(build_dir, ".lock"), "w")
    fcntl.flock(lock_file, fcntl.LOCK_SH)
    print("got lock on %s" % lock_file)
```

**Comment by YunqiuXu** [comment] 2018-11-13 07:21
Hi, thanks for your response. I tried your script but still got error, here is the output:

In [6]: print("base dir: %s" % base_dir)
   ...: print("releases dir: %s" % releases_dir)
   ...: print("build name: %s" % build_name)
   ...: 
   ...: 
base dir: /home/yunqxu/.ai2thor
releases dir: /home/yunqxu/.ai2thor/releases
build name: thor-201810021256-Linux64
In [7]: build_dir = os.path.join(releases_dir, build_name)
In [8]: if os.path.isdir(build_dir):
   ...:     lock_file = open(os.path.join(build_dir, ".lock"), "w")
   ...:     fcntl.flock(lock_file, fcntl.LOCK_SH)
   ...:     print("got lock on %s" % lock_file)
   ...:     
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-8-97278dff1950> in <module>()
      1 if os.path.isdir(build_dir):
      2     lock_file = open(os.path.join(build_dir, ".lock"), "w")
----> 3     fcntl.flock(lock_file, fcntl.LOCK_SH)
      4     print("got lock on %s" % lock_file)
      5 
OSError: [Errno 9] Bad file descriptor


Here is my RedHat version:
LSB Version:	:core-4.1-amd64:core-4.1-ia32:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-ia32:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-ia32:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch:trialuse-4.1-amd64:trialuse-4.1-noarch
Distributor ID:	RedHatEnterpriseWorkstation
Description:	Red Hat Enterprise Linux Workstation release 7.3 (Maipo)
Release:	7.3
Codename:	Maipo

**Comment by ekolve** [comment] 2018-11-13 19:19
Can you paste the output from the command?
`mount`
I am curious if the filesystem is remote.

For the time being though, you can get around this error by adding the following code:

```python
import ai2thor.controller

def noop(self):
    pass

ai2thor.controller.Controller.lock_release = noop
ai2thor.controller.Controller.unlock_release = noop
ai2thor.controller.Controller.prune_releases = noop
# your code here
```
I am not sure that RHEL 7.3 has the versions of OpenGL that Unity depends on, so you may still receive an error after running start.  If that is the case, take a look in:
$HOME/.config/unity3d/Allen Institute for Artificial Intelligence/AI2-Thor/Player.log

and look for an error.  If docker can be installed on this machine, than its possible to run with that instead.

**Comment by YunqiuXu** [comment] 2018-11-15 02:46
Hi, sorry for late response. Here is the output of `mount` command:

```
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
devtmpfs on /dev type devtmpfs (rw,nosuid,size=131913304k,nr_inodes=32978326,mode=755)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,nodev,mode=755)
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,mode=755)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd)
pstore on /sys/fs/pstore type pstore (rw,nosuid,nodev,noexec,relatime)
cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (rw,nosuid,nodev,noexec,relatime,net_prio,net_cls)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpuacct,cpu)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,nosuid,nodev,noexec,relatime,pids)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,nodev,noexec,relatime,perf_event)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,nosuid,nodev,noexec,relatime,hugetlb)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)
configfs on /sys/kernel/config type configfs (rw,relatime)
/dev/sda6 on / type xfs (rw,relatime,attr2,inode64,noquota)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=31,pgrp=1,timeout=300,minproto=5,maxproto=5,direct,pipe_ino=14172)
debugfs on /sys/kernel/debug type debugfs (rw,relatime)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime)
mqueue on /dev/mqueue type mqueue (rw,relatime)
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,relatime)
nfsd on /proc/fs/nfsd type nfsd (rw,relatime)
/dev/sdb1 on /scratch type xfs (rw,relatime,attr2,inode64,noquota)
/dev/sda2 on /tmp type xfs (rw,relatime,attr2,inode64,noquota)
/dev/sda3 on /var type xfs (rw,relatime,attr2,inode64,noquota)
sunrpc on /var/lib/nfs/rpc_pipefs type rpc_pipefs (rw,relatime)
/dev/sda1 on /boot type xfs (rw,relatime,attr2,inode64,noquota)
tmpfs on /run/user/42 type tmpfs (rw,nosuid,nodev,relatime,size=26385664k,mode=700,uid=42,gid=42)
fusectl on /sys/fs/fuse/connections type fusectl (rw,relatime)
mdcislresnfs03.adsroot.uts.edu.au:/ifs/mdcisl01/research/facility/ihpc/rhel7homes on /home type nfs (rw,relatime,vers=3,rsize=131072,wsize=524288,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=138.25.54.231,mountvers=3,mountport=300,mountproto=tcp,local_lock=none,addr=138.25.54.231)
mdcislresnfs03.adsroot.uts.edu.au:/ifs/mdcisl01/research/facility/ihpc/projects on /projects type nfs (rw,relatime,vers=3,rsize=131072,wsize=524288,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=138.25.54.231,mountvers=3,mountport=300,mountproto=tcp,local_lock=none,addr=138.25.54.231)
mdcislresnfs03.adsroot.uts.edu.au:/ifs/mdcisl01/research/facility/ihpc/share on /share type nfs (rw,relatime,vers=3,rsize=131072,wsize=524288,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=138.25.54.231,mountvers=3,mountport=300,mountproto=tcp,local_lock=none,addr=138.25.54.231)
mdcislresnfs03.adsroot.uts.edu.au:/ifs/mdcisl01/research/facility/ihpc/data on /data type nfs (rw,relatime,vers=3,rsize=131072,wsize=524288,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=138.25.54.231,mountvers=3,mountport=300,mountproto=tcp,local_lock=none,addr=138.25.54.231)
tmpfs on /run/user/36812 type tmpfs (rw,nosuid,nodev,relatime,size=26385664k,mode=700,uid=36812,gid=5010)
tmpfs on /run/user/36121 type tmpfs (rw,nosuid,nodev,relatime,size=26385664k,mode=700,uid=36121,gid=5010)
tmpfs on /run/user/37467 type tmpfs (rw,nosuid,nodev,relatime,size=26385664k,mode=700,uid=37467,gid=5010)
tmpfs on /run/user/43717 type tmpfs (rw,nosuid,nodev,relatime,size=26385664k,mode=700,uid=43717,gid=5010)
```

I still encountered error after adding the new code. And I could not navigate to Player.log for that `$HOME/.config/unity3d` does not exist. Is it the reason for error "Bad file descriptor"?

**Comment by ekolve** [comment] 2018-11-15 20:15
Are you getting the same error as before? Can you post the stack trace?  If you are getting the same error, the stack trace should be different if you applied the new code changes.

**Comment by ekolve** [comment] 2020-06-23 18:03
Did you ever discover the cause of this error and/or is this error still occurring?

**Comment by mattdeitke** [comment] 2020-08-14 02:11
Closing due to inactivity. Feel free to re-open if there are follow-ups.

**Closed by mattdeitke** 2020-08-14 02:11 UTC
